export default {
  GET_PROJECTS: 'GET_PROJECTS',
  SET_PROJECTS: 'SET_PROJECTS',
  SET_PROJECT: 'SET_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  ADD_NEW_PROJECT: 'ADD_NEW_PROJECT',
  UPDATE_TRANSLATION: 'UPDATE_TRANSLATION',
  ADD_KEY_TRANSLATION: 'ADD_KEY_TRANSLATION',
  DELETE_KEY_TRANSLATION: 'DELETE_KEY_TRANSLATION',
};
