export default {
  GET_PROJECTS: 'GET_PROJECTS',
  SET_PROJECTS: 'SET_PROJECTS',
  SET_PROJECT: 'SET_PROJECT',
  UPDATE_TRANSLATION: 'UPDATE_TRANSLATION',
  ADD_KEY_TRANSLATION: 'ADD_KEY_TRANSLATION'
};
